name: ci

on:
  push:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos
      COMMIT: ${{ github.sha }}
      REPO: shipping
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml

      - name: Unit Tests
        run: mvn -q test

      - name: Integration Tests
        run: mvn integration-test

     
      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "gunareddy7" --password-stdin 

      - name: Push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
        with:
         dockerfile: docker/shipping/Dockerfile
         path: target/
         registry: docker.io
         image: gunareddy7/sockshop
          #tag_with_ref:true
          #tag_with_sha:true
